### ISSUE TITLE
type error found on https://www.movedid.build

### ISSUE THREAD

**Issue by 0xOutOfGas** [NonceGeek/MoveDID#44]
Lmpl should be Impl, short for implementation?
![image](https://user-images.githubusercontent.com/111507345/204509396-11e709bd-13b4-4342-a36c-9f1b0b73e573.png)

**Comment by Blockchain-Key** [comment]
🙋🏻‍♀️

**Comment by Blockchain-Key** [comment]
https://www.movedid.build/

**Comment by Blockchain-Key** [comment]
已修改
