### ISSUE TITLE
DID manager is not work on https://manager.movedid.build/

### ISSUE THREAD

**Issue by 0xOutOfGas** [NonceGeek/MoveDID#45]
connect wallet testnet, click "INIT ADDRAGGR IN DID CONTRACT",
![image](https://user-images.githubusercontent.com/111507345/204509690-f9c86d0a-71d0-4efb-ab20-6491248a87e2.png)

Launch wallet, got below error
<img width="196" alt="6ebdbcefa2d2fc1a810d37490e04547" src="https://user-images.githubusercontent.com/111507345/204509555-7a9bfeb0-2a1d-4c24-b4c5-32c7e302d08e.png">

**Comment by zhenfeng-zhu** [comment]
Hello, does this error still exist?

**Comment by 0xOutOfGas** [comment]
tried again， it's ok now
